Improvements
oasisprotocol/demo-voting pull request #11
Opened 2023-07-17 18:53 UTC by lubej

- Add MetaMask install button, in case MetaMask is not installed;
- Improve edge cases;
- remove infinite loops;

2023-07-19 11:00 UTC, buberdds approved these changes

2023-07-19 11:00 UTC, buberdds commented on frontend/src/stores/ethereum.ts
> +                blockExplorerUrls: ['https://explorer.sapphire.oasis.io'],
Can we switch urls to an official explorer in both `blockExplorerUrls`?

2023-07-19 11:00 UTC, buberdds commented on frontend/src/components/AccountPicker.vue
> +    <span class="account-picker-content" v-else-if="!isMetaMaskInstalled">
parent should be a button

2023-08-16 11:40 UTC, matevz requested changes
I tested this locally and there a still some edges to be polished.

2023-08-16 11:40 UTC, matevz commented on frontend/src/components/AccountPicker.vue
> +  if (!isMetaMaskInstalled.value) {
Can you also fix the mouse pointer resembling something clickable over the connect wallet button.

![image](https://github.com/oasisprotocol/demo-voting/assets/83672/c87efa21-1590-441e-b3f7-2586ffbcdade)

2023-08-16 11:40 UTC, matevz commented on frontend/src/views/HomeView.vue
> +  await eth.switchNetwork(Network.FromConfig);
Not sure why, but this didn't trigger the network switch from Sapphire Mainnet (using it previously for sth else) to Hardhat Localnet (having it set in .env.development). It triggered the switch once I clicked on the new poll button (in PollView.vue). Can you take a look?

2023-08-16 11:40 UTC, matevz commented on frontend/src/components/AccountPicker.vue
> +        <span>Install MetaMask</span>
Ideally this should be shown immediately in place of the "Connect Wallet" button, if Metamask is not installed.

2023-08-22 11:47 UTC, matevz commented
FYI gasless voting was merged into master branch. Please rebase.

2023-09-11 16:56 UTC, lubej commented on frontend/src/views/HomeView.vue
> +  await eth.switchNetwork(Network.FromConfig);
Sometimes the notification from MetaMask gets hidden, for the network change request. Did add the hard reload for the page to ensure that data gets refresh after network change, let me know if it works for you.

2023-09-13 11:47 UTC, matevz approved these changes
Good job. LGTM. FYI I already deployed this to https://playground.oasis.io/demo-voting

2023-09-13 11:49 UTC, merged