Contract Self-Signed gasless poll creation & voting
oasisprotocol/demo-voting pull request #9
Opened 2023-07-16 02:06 UTC by CedarMist

This hoists my previous gasless voting PR onto the new design + fixes lots of UX things which made it tedious to use.

2023-07-16 08:08 UTC, matevz requested changes, later dismissed
First pass, I didn't test it yet, will do it later.

I suggest we have demo-voting supporting all three mechanisms:
- payable votes (current master branch)
- GSN votes
- gasless votes (we should come up with a fancy Oasis name for it?)

That being said I would not merge this until we cleanup the backend/contracts:
- EIP155Signer.sol should become part of @oasisprotocol/sapphire-contracts
- IERC165 should just be included from openzeppelin?
- RLPWriter should be part of @oasisprotocol/sapphire-contracts
- DAOv1 should be an interface with three implementations mentioned above

If we don't make it for EthCC, it's even fine to have it in a separate PRs for now.

Thoughts?

2023-07-16 08:08 UTC, matevz commented on frontend/src/views/CreatePollView.vue
> +import { useDAOv1, useGaslessVoting, useUnwrappedDAOv1, useUnwrappedGaslessVoting } from '../contracts';
Could you move this to a separate PR please? I would need that for my GSN voting as well and let's merge it separately ;)

2023-07-16 08:08 UTC, matevz commented on frontend/src/contracts.ts
> +export function useUnwrappedDAOv1(): ComputedRef<DAOv1> {
Could you move `useUnwrappedDAO` and `useUnwrappedPollACLv1` to a separate PR please? I would need that for my GSN voting as well and let's merge it separately ;)

2023-07-16 10:56 UTC, CedarMist commented
Good idea to move the EIP155Signer and RLPWriter to sapphire-contracts.

The unwrapped providers are kinda messy, could have an extra PR for them or
could just have 3 branches and copy what you need.

Would prefer to make finishing touches for deployment to mainnet on my
branch.

On Sun, Jul 16, 2023, 09:08 Matevž Jekovec ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> First pass, I didn't test it yet, will do it later.
>
> I suggest we have demo-voting supporting all three mechanisms:
>
>    - payable votes (current master branch)
>    - GSN votes
>    - gasless votes (we should come up with a fancy Oasis name for it?)
>
> That being said I would not merge this until we cleanup the
> backend/contracts:
>
>    - EIP155Signer.sol should become part of
>    @oasisprotocol/sapphire-contracts
>    - IERC165 should just be included from openzeppelin?
>    - RLPWriter should be part of @oasisprotocol/sapphire-contracts
>    - DAOv1 should be an interface with three implementations mentioned
>    above
>
> If we don't make it for EthCC, it's even fine to have it in a separate PRs
> for now.
>
> Thoughts?
> ------------------------------
>
> In frontend/src/views/CreatePollView.vue
> <https://github.com/oasisprotocol/demo-voting/pull/9#discussion_r1264635484>
> :
>
> >
> -import { useDAOv1 } from '../contracts';
> +import { useDAOv1, useGaslessVoting, useUnwrappedDAOv1, useUnwrappedGaslessVoting } from '../contracts';
>
> Could you move this to a separate PR please? I would need that for my GSN
> voting as well and let's merge it separately ;)
> ------------------------------
>
> In frontend/src/contracts.ts
> <https://github.com/oasisprotocol/demo-voting/pull/9#discussion_r1264635683>
> :
>
> > @@ -25,10 +25,72 @@ export function useDAOv1(): ComputedRef<DAOv1> {
>    });
>  }
>
> +export function useUnwrappedDAOv1(): ComputedRef<DAOv1> {
>
> Could you move useUnwrappedDAO and useUnwrappedPollACLv1 to a separate PR
> please? I would need that for my GSN voting as well and let's merge it
> separately ;)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/oasisprotocol/demo-voting/pull/9#pullrequestreview-1531698516>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BADVSAYXZ3GYLMURQUAH3TLXQOOOZANCNFSM6AAAAAA2LUEYKE>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-07-16 16:30 UTC, CedarMist commented
> DAOv1 should be an interface with three implementations mentioned above

There is no need for DAOv1 to be an interface.

GSN implementation can use the same pattern as I did with GaslessVoting.

 - DAOv1 is assigned an optional 'proxy voter' contract, aka a trusted verifier which can override `msg.sender`
 - GSN contract interfaces with DAOv1 via `proxyVote` interface
 - Client detects which proxy voter implementation is being used, via ERC-165

2023-08-18 17:57 UTC, CedarMist commented
I can't merge this because it's my branch. You will need to approve it.

2023-08-21 10:38 UTC, matevz approved these changes

2023-08-21 10:39 UTC, merged